# Generated by Django 4.2 on 2023-05-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitat', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.BigIntegerField()),
                ('aname', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('specices', models.CharField(max_length=256)),
                ('date_of_death', models.DateField(null=True)),
                ('date_of_arrival', models.DateField()),
                ('last_updated', models.DateField(null=True)),
                ('Habitat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitat.habitat')),
            ],
        ),
    ]
