# Generated by Django 4.2 on 2023-05-08 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0002_habitat_last_updated'),
        ('aimals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animals',
            name='id',
        ),
        migrations.AddField(
            model_name='animals',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='Habitat_id',
            field=models.ForeignKey(db_column='Habitat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitat.habitat'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='animal_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
