# Generated by Django 4.2 on 2023-05-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimals', '0002_remove_animals_id_animals_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
