# Generated by Django 4.2 on 2023-05-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='last_updated',
            field=models.DateField(null=True),
        ),
    ]
